# backend = "glx";
# glx-copy-from-front = false;
#
# active-opacity = 1;
# inactive-opacity = 1;
# frame-opacity = 1;
# inactive-opacity-override = false;
# blur-background = true;
# blur-background-exclude = [
#   "window_type = 'dock'",
# ];
#
# blur-method = "dual_kawase";
# blur-strength = 8;

fading = true;
fade-delta = 2;
no-fading-openclose = false;

fade-exclude = [ ];

wintypes:
{
  dock = {
    shadow = false;
  };
};

# opacity-rule = [
#   "90:class_g = 'URxvt'",
#   "90:class_g = 'Alacritty' && focused",
#   "70:class_g = 'Alacritty' && !focused"
# ];
