[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dimensions = { columns = 85, lines = 30 }
padding = { x = 10, y = 4 }
dynamic_padding = false
opacity = 0.9

[font]
size = 11

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[font.bold]
family = "BerkeleyMono Nerd Font"
style = "Bold"

[font.italic]
family = "BerkeleyMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "BerkeleyMono Nerd Font"
style = "Bold Italic"

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Block", blinking = "Off" }

# Darkmatter
[colors.primary]
background = "#121113"
foreground = "#ffffff"

[colors.cursor]
text = "#121113"
cursor = "#ffffff"

[colors.selection]
text = "#000000"
background = "#222222"

[colors.normal]
black = "#121113"
red = "#5f8787"
green = "#fbcb97"
yellow = "#e78a53"
blue = "#888888"
magenta = "#999999"
cyan = "#aaaaaa"
white = "#c1c1c1"

[colors.bright]
black = "#333333"
red = "#5f8787"
green = "#fbcb97"
yellow = "#e78a53"
blue = "#888888"
magenta = "#999999"
cyan = "#aaaaaa"
white = "#c1c1c1"
