import = ["/Users/stevedsimkins/.config/alacritty/poimandres.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "CommitMono Nerd Font"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011T"
key = "K"
mods = "Command"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 85
lines = 30

[window.padding]
x = 10
y = 4
