#!/bin/sh
# Requires: dmenu, libnotify, ifupdown-ng, doas
# dmenu counterpart of eth0-disable.
set -u

IFACE="${1:-eth0}"
NOTIFY_ID=7304

notify() {
    if command -v dunstify >/dev/null 2>&1; then
        dunstify -r "$NOTIFY_ID" ${2:+-u "$2"} "Network" "$1"
    else
        notify-send ${2:+-u "$2"} "Network" "$1"
    fi
}

fail() { notify "$1" critical; exit 1; }

doas -n true 2>/dev/null || fail "doas needs a password; add a nopass rule for this user."

[ "$(printf 'No\nYes\n' | dmenu -c -i -l 2 -p "Disable $IFACE?")" = "Yes" ] || exit 0

notify "Disabling $IFACE..."

doas sh -c '
    ifdown "$1" 2>/dev/null
    ip link set "$1" down
' _ "$IFACE"

notify "$IFACE disabled"
