;;; darkmatter-theme.el --- Darkmatter on base16 -*- lexical-binding: t; -*-

;; https://darkmattertheme.com
;; Palette + a few overrides on top of `base16-theme' (package base16-theme).
;; The 16 slots are mapped to match the old doom-darkmatter roles.

(require 'base16-theme)

(defvar darkmatter-theme-colors
  '(:base00 "#121113"   ; background
    :base01 "#1a191a"   ; lighter background (highlight)
    :base02 "#222222"   ; selection
    :base03 "#555555"   ; comments
    :base04 "#777777"   ; doc, dark foreground
    :base05 "#c1c1c1"   ; foreground
    :base06 "#d0d0d0"   ; light foreground
    :base07 "#e8e8e8"   ; lightest
    :base08 "#aa6c6c"   ; red: errors
    :base09 "#e78a53"   ; orange: warnings, accents
    :base0A "#e78a53"   ; types
    :base0B "#fbcb97"   ; strings
    :base0C "#5f8787"   ; teal
    :base0D "#888888"   ; functions
    :base0E "#999999"   ; keywords
    :base0F "#8a5a5a")  ; deprecated
  "Darkmatter colors, in base16 slot order.")

(deftheme darkmatter "Darkmatter, based on Black Metal Bathory.")

;; Fringe/line numbers share the main background, like doom-darkmatter
(setq base16-theme-distinct-fringe-background nil)

(base16-theme-define 'darkmatter darkmatter-theme-colors)

;; Where doom-darkmatter differs from stock base16 role assignments
(custom-theme-set-faces
 'darkmatter
 '(cursor                      ((t (:background "#e78a53"))))
 '(font-lock-variable-name-face ((t (:foreground "#5f8787"))))
 '(font-lock-builtin-face      ((t (:foreground "#999999"))))
 '(font-lock-constant-face     ((t (:foreground "#aaaaaa"))))
 '(font-lock-number-face       ((t (:foreground "#aaaaaa"))))
 '(font-lock-warning-face      ((t (:foreground "#e78a53"))))
 '(mode-line                   ((t (:foreground "#c1c1c1" :background "#121113" :overline "#222222" :box nil))))
 '(mode-line-inactive          ((t (:foreground "#777777" :background "#121113" :overline "#222222" :box nil))))
 '(mode-line-buffer-id         ((t (:foreground "#c1c1c1" :weight bold))))
 '(line-number                 ((t (:foreground "#333333" :background "#121113"))))
 '(line-number-current-line    ((t (:foreground "#e78a53" :background "#121113"))))
 '(vertical-border             ((t (:foreground "#222222"))))
 '(erc-prompt-face             ((t (:foreground "#e78a53" :weight bold))))

 ;; Packages base16 has no faces for
 '(elfeed-search-date-face          ((t (:foreground "#aaaaaa"))))
 '(elfeed-search-feed-face          ((t (:foreground "#888888"))))
 '(elfeed-search-tag-face           ((t (:foreground "#555555"))))
 '(elfeed-search-title-face         ((t (:foreground "#555555"))))
 '(elfeed-search-unread-title-face  ((t (:foreground "#c1c1c1" :weight bold))))
 '(elfeed-search-unread-count-face  ((t (:foreground "#e78a53"))))
 '(elfeed-search-filter-face        ((t (:foreground "#aaaaaa"))))
 '(elfeed-log-debug-level-face      ((t (:foreground "#555555"))))
 '(elfeed-log-error-level-face      ((t (:inherit error))))
 '(elfeed-log-info-level-face       ((t (:inherit success))))
 '(elfeed-log-warn-level-face       ((t (:inherit warning))))
 '(which-key-key-face               ((t (:foreground "#e78a53"))))
 '(which-key-group-description-face ((t (:foreground "#999999"))))
 '(which-key-command-description-face ((t (:foreground "#c1c1c1")))))

;; Magit/diff/org/vc faces, flattened from doom-darkmatter
(custom-theme-set-faces
 'darkmatter
 '(diff-hl-change ((t (:foreground "#e78a53" :background "#e78a53"))))
 '(diff-hl-delete ((t (:foreground "#aa6c6c" :background "#aa6c6c"))))
 '(diff-hl-insert ((t (:foreground "#fbcb97" :background "#fbcb97"))))
 '(diff-added ((t (:inherit hl-line :foreground "#fbcb97"))))
 '(diff-changed ((t (:foreground "#aaaaaa"))))
 '(diff-context ((t (:foreground "#a9a9a9"))))
 '(diff-removed ((t (:foreground "#aa6c6c" :background "#222222"))))
 '(diff-header ((t (:foreground "#aaaaaa"))))
 '(diff-file-header ((t (:foreground "#888888"))))
 '(diff-hunk-header ((t (:foreground "#aaaaaa"))))
 '(diff-indicator-added ((t (:foreground "#fbcb97"))))
 '(diff-indicator-changed ((t (:foreground "#e78a53"))))
 '(diff-indicator-removed ((t (:foreground "#aa6c6c"))))
 '(diff-refine-added ((t (:inherit diff-added :inverse-video t))))
 '(diff-refine-changed ((t (:inherit diff-changed :inverse-video t))))
 '(diff-refine-removed ((t (:inherit diff-removed :inverse-video t))))
 '(ediff-fine-diff-A ((t (:inherit diff-refine-removed))))
 '(ediff-fine-diff-B ((t (:inherit diff-refine-added))))
 '(ediff-fine-diff-C ((t (:inherit ediff-fine-diff-A))))
 '(ediff-current-diff-A ((t (:foreground "#aa6c6c" :background "#3d3030" :extend t))))
 '(ediff-current-diff-B ((t (:foreground "#fbcb97" :background "#40362d" :extend t))))
 '(ediff-current-diff-C ((t (:inherit ediff-current-diff-A))))
 '(ediff-even-diff-A ((t (:inherit hl-line))))
 '(ediff-even-diff-B ((t (:inherit ediff-even-diff-A))))
 '(ediff-even-diff-C ((t (:inherit ediff-even-diff-A))))
 '(ediff-odd-diff-A ((t (:inherit ediff-even-diff-A))))
 '(ediff-odd-diff-B ((t (:inherit ediff-odd-diff-A))))
 '(ediff-odd-diff-C ((t (:inherit ediff-odd-diff-A))))
 '(git-commit-summary ((t (:foreground "#fbcb97"))))
 '(git-commit-overlong-summary ((t (:inherit error :background "#0b0a0b" :slant italic :weight bold))))
 '(git-commit-nonempty-second-line ((t (:inherit git-commit-overlong-summary))))
 '(git-commit-keyword ((t (:foreground "#aaaaaa" :slant italic))))
 '(git-commit-pseudo-header ((t (:foreground "#777777" :slant italic))))
 '(git-commit-known-pseudo-header ((t (:foreground "#777777" :weight bold :slant italic))))
 '(git-commit-comment-branch-local ((t (:foreground "#999999"))))
 '(git-commit-comment-branch-remote ((t (:foreground "#fbcb97"))))
 '(git-commit-comment-detached ((t (:foreground "#e78a53"))))
 '(git-commit-comment-heading ((t (:foreground "#999999"))))
 '(git-commit-comment-file ((t (:foreground "#aaaaaa"))))
 '(git-commit-comment-action ((t nil)))
 '(hl-line ((t (:background "#121113" :extend t))))
 '(magit-bisect-bad ((t (:foreground "#aa6c6c"))))
 '(magit-bisect-good ((t (:foreground "#fbcb97"))))
 '(magit-bisect-skip ((t (:foreground "#e78a53"))))
 '(magit-blame-hash ((t (:foreground "#aaaaaa"))))
 '(magit-blame-date ((t (:foreground "#aa6c6c"))))
 '(magit-blame-heading ((t (:foreground "#e78a53" :background "#222222" :extend t))))
 '(magit-branch-current ((t (:foreground "#888888"))))
 '(magit-branch-local ((t (:foreground "#aaaaaa"))))
 '(magit-branch-remote ((t (:foreground "#fbcb97"))))
 '(magit-cherry-equivalent ((t (:foreground "#aaaaaa"))))
 '(magit-cherry-unmatched ((t (:foreground "#aaaaaa"))))
 '(magit-diff-added ((t (:foreground "#c8a278" :background "#292320" :extend t))))
 '(magit-diff-added-highlight ((t (:foreground "#fbcb97" :background "#40362d" :weight bold :extend t))))
 '(magit-diff-base ((t (:foreground "#b86e42" :background "#271d19" :extend t))))
 '(magit-diff-base-highlight ((t (:foreground "#e78a53" :background "#3c291f" :weight bold :extend t))))
 '(magit-diff-context ((t (:foreground "#737373" :background "#121113" :extend t))))
 '(magit-diff-context-highlight ((t (:foreground "#c1c1c1" :background "#121113" :extend t))))
 '(magit-diff-file-heading ((t (:foreground "#c1c1c1" :weight bold :extend t))))
 '(magit-diff-file-heading-selection ((t (:foreground "#999999" :background "#666666" :weight bold :extend t))))
 '(magit-diff-hunk-heading ((t (:foreground "#121113" :background "#3f3e40" :extend t))))
 '(magit-diff-hunk-heading-highlight ((t (:foreground "#121113" :background "#aaaaaa" :weight bold :extend t))))
 '(magit-diff-lines-heading ((t (:foreground "#e78a53" :background "#aa6c6c" :extend t :extend t))))
 '(magit-diff-removed ((t (:foreground "#885656" :background "#2f2929" :extend t))))
 '(magit-diff-removed-highlight ((t (:foreground "#aa6c6c" :background "#3d3030" :weight bold :extend t))))
 '(magit-diffstat-added ((t (:foreground "#fbcb97"))))
 '(magit-diffstat-removed ((t (:foreground "#aa6c6c"))))
 '(magit-dimmed ((t (:foreground "#999999"))))
 '(magit-hash ((t (:foreground "#555555"))))
 '(magit-header-line ((t (:background "#666666" :foreground "#c1c1c1" :weight bold :box (:line-width 3 :color "#666666")))))
 '(magit-filename ((t (:foreground "#aaaaaa"))))
 '(magit-log-author ((t (:foreground "#e78a53"))))
 '(magit-log-date ((t (:foreground "#888888"))))
 '(magit-log-graph ((t (:foreground "#555555"))))
 '(magit-process-ng ((t (:inherit error))))
 '(magit-process-ok ((t (:inherit success))))
 '(magit-reflog-amend ((t (:foreground "#999999"))))
 '(magit-reflog-checkout ((t (:foreground "#888888"))))
 '(magit-reflog-cherry-pick ((t (:foreground "#fbcb97"))))
 '(magit-reflog-commit ((t (:foreground "#fbcb97"))))
 '(magit-reflog-merge ((t (:foreground "#fbcb97"))))
 '(magit-reflog-other ((t (:foreground "#aaaaaa"))))
 '(magit-reflog-rebase ((t (:foreground "#999999"))))
 '(magit-reflog-remote ((t (:foreground "#aaaaaa"))))
 '(magit-reflog-reset ((t (:inherit error))))
 '(magit-refname ((t (:foreground "#555555"))))
 '(magit-section-heading ((t (:foreground "#888888" :weight bold :extend t))))
 '(magit-section-heading-selection ((t (:foreground "#e78a53" :weight bold :extend t))))
 '(magit-section-highlight ((t (:inherit hl-line))))
 '(magit-section-secondary-heading ((t (:foreground "#aaaaaa" :weight bold :extend t))))
 '(magit-sequence-drop ((t (:foreground "#aa6c6c"))))
 '(magit-sequence-head ((t (:foreground "#888888"))))
 '(magit-sequence-part ((t (:foreground "#e78a53"))))
 '(magit-sequence-stop ((t (:foreground "#fbcb97"))))
 '(magit-signature-bad ((t (:inherit error))))
 '(magit-signature-error ((t (:inherit error))))
 '(magit-signature-expired ((t (:foreground "#e78a53"))))
 '(magit-signature-good ((t (:inherit success))))
 '(magit-signature-revoked ((t (:foreground "#999999"))))
 '(magit-signature-untrusted ((t (:foreground "#e78a53"))))
 '(magit-tag ((t (:foreground "#e78a53"))))
 '(org-block ((t (:background "#222222" :extend t))))
 '(org-block-background ((t (:background "#222222" :extend t))))
 '(org-block-begin-line ((t (:inherit org-block :foreground "#555555"))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-checkbox ((t (:inherit org-todo))))
 '(org-checkbox-statistics-done ((t (:inherit org-done))))
 '(org-checkbox-statistics-todo ((t (:inherit org-todo))))
 '(org-code ((t (:inherit org-block :foreground "#e78a53"))))
 '(org-date ((t (:foreground "#e78a53"))))
 '(org-document-info ((t (:foreground "#999999"))))
 '(org-document-title ((t (:foreground "#999999" :weight bold))))
 '(org-done ((t (:inherit org-headline-done :strike-through unspecified :weight bold))))
 '(org-link ((t (:inherit link :foreground "#e78a53"))))
 '(org-meta-line ((t (:foreground "#777777"))))
 '(org-table ((t (:foreground "#aaaaaa"))))
 '(org-tag ((t (:foreground "#777777" :weight normal))))
 '(org-todo ((t (:foreground "#fbcb97" :bold inherit))))
 '(org-verbatim ((t (:foreground "#fbcb97"))))
 '(outline-1 ((t (:foreground "#888888" :weight bold :extend t))))
 '(outline-2 ((t (:foreground "#999999" :weight bold :extend t))))
 '(outline-3 ((t (:foreground "#aaaaaa" :weight bold :extend t))))
 '(outline-4 ((t (:foreground "#a5a5a5" :weight bold :extend t))))
 '(outline-5 ((t (:foreground "#b2b2b2" :weight bold :extend t))))
 '(outline-6 ((t (:foreground "#c3c3c3" :weight bold :extend t))))
 '(outline-7 ((t (:foreground "#cccccc" :weight bold :extend t))))
 '(outline-8 ((t (:foreground "#e7e7e7" :weight bold :extend t))))
 '(smerge-lower ((t (:background "#40362d"))))
 '(smerge-upper ((t (:background "#3d3030"))))
 '(smerge-base ((t (:background "#29282a"))))
 '(smerge-markers ((t (:background "#555555" :foreground "#121113" :distant-foreground "#c1c1c1" :weight bold))))
 '(smerge-refined-added ((t (:inherit diff-added :inverse-video t))))
 '(smerge-refined-removed ((t (:inherit diff-removed :inverse-video t))))
 '(smerge-mine ((t (:background "#3d3030"))))
 '(smerge-other ((t (:background "#40362d")))))

(provide-theme 'darkmatter)

;;; darkmatter-theme.el ends here
